# Jekyll configuration of @lepus2589's GitHub pages profile page
# Copyright (C) 2023  Tim Kaune

# Except where otherwise noted, this document is licensed under a
# [Creative Commons Attribution-ShareAlike 4.0 International License](https://creativecommons.org/licenses/by-sa/4.0/).

title: Rabbit Hole - Home to @lepus2589
description: |
  This is the web presence of @lepus2589. Here, you can find PGP keys, keyoxide
  profiles and the like.

remote_theme: pages-themes/cayman@v0.2.0

plugins:
  - jekyll-remote-theme
  - jemoji

timezone: Europe/Berlin

exclude:
  - LICENSE
  - README.md
